POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.NWM2ZDZiMWZhMmExMjY1MWExYzQ3ZjYw.Thv77r1YUYV5MqAsywtUrzUB0XsKii0eTUGzO8S8VHI
Content-Type: application/json

{
  "title": "Italialainen pestopasta",
  "author": "Kotiruokaaa",
  "url": "www.blogilista.fi/polku",
  "likes": 2
}